# Generated by Django 3.2.4 on 2021-06-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=256, verbose_name='first name')),
                ('last_name', models.CharField(max_length=256, verbose_name='last name')),
                ('designation', models.CharField(max_length=256, verbose_name='designation')),
                ('profile_image', models.ImageField(upload_to='profile_image/%Y/%m/%d/')),
                ('facebook', models.URLField(max_length=128, verbose_name='facebook')),
                ('twitter', models.URLField(max_length=128, verbose_name='twitter')),
                ('google_plus', models.URLField(max_length=128, verbose_name='google_plus')),
                ('create_data', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
            },
        ),
    ]
