# Generated by Django 3.2.4 on 2021-06-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_cars_mileage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'verbose_name': 'Cars', 'verbose_name_plural': 'Cars'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Images', 'verbose_name_plural': 'Images'},
        ),
        migrations.RenameField(
            model_name='images',
            old_name='product',
            new_name='cars',
        ),
        migrations.AlterField(
            model_name='cars',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='featured'),
        ),
    ]
