# Generated by Django 3.2.4 on 2021-06-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20210616_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='car',
            field=models.ForeignKey(blank=True, default='not authenticated', on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.cars', verbose_name='car id'),
        ),
    ]
